version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: update-pip
          command: 'pip install -U pip'
      - run:
          name: install-deps
          command: pip install -r requirements.txt
      - run:
          name: install-nalangen
          command:  pushd project && pip install -e . && popd
      - run:
          name: test
          command: pushd project && pytest && popd
